# See: https://taskfile.dev/api/

version: "3"

tasks:
  migrate:
    aliases:
      - migrate
    desc: "Apply migrations"
    cmds:
      - go run cmd/migrator/main.go -storage-path ./storage/sso.db -migrations-path ./migrations -migrations-table migrations
  start:
    aliases:
      - start
    desc: "Start the application"
    cmds:
      - go run cmd/sso/main.go -config ./config/local.yaml
